Task1
opro12/learn-homework-1 pull request #1
Opened 2022-09-16 16:37 UTC by opro12

Готовы первые семь задач)

2022-09-16 18:20 UTC, vppuzakov requested changes
В целом все верно, но есть комменты для инфо с рекомендацией попробовать, есть и важные моменты которые лучше поправить

2022-09-16 18:20 UTC, vppuzakov commented on except_1.py
> +  return phrase
💡  Этот `return phase` из функции не используется в 27 строке - можно удалить

2022-09-16 18:20 UTC, vppuzakov commented on except_1.py
> +          #print('Неправильный ответ')
💡 закомментированные строчки кода лучше удалить

2022-09-16 18:20 UTC, vppuzakov commented on except_1.py
> +  try:
👍 отлично сделана обработка ошибки try ... except

2022-09-16 18:20 UTC, vppuzakov commented on except_1.py
>      hello_user()
💡 именно эту ошибку с KeyboardInterrupt обычно делают внутри самой main функции, а не в функции с логикой (в нашем случае `hello_user`)

2022-09-16 18:20 UTC, vppuzakov commented on except_2.py
>      print(discounted(100, 2))
💡 посмотри, что будет, если в функцию передать 101 в размер скидки

2022-09-16 18:20 UTC, vppuzakov commented on except_2.py
> +        if max_discount >= 100:
💡 не совсем получим верное поведение функции, когда передадим 101
сработает ValueError, который будет перехвачен в 28 строке и выдан результат - неверный тип данных - хотя ошибка то в другом

2022-09-16 18:20 UTC, vppuzakov commented on except_2.py
> +        if max_discount >= 100:
Поэтому лучше райзить свой тип ошибки (AppError) - как его сделать - посмотри в видео нашей группы

2022-09-16 18:20 UTC, vppuzakov commented on except_2.py
> +    except (ValueError, TypeError):
👍 обработал две ошибки - не важно в каком месте из трех (18-20 строчки) они произойдут

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_1.py
> +    age = int(age)
💡 старайся не менять тип переменной, а использовать новую, лучше в функцию уже передавать число, а преобразование сделать в 35-й строке (как у тебя кстати уже происходит)

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_1.py
> +def age_verification(age):
👍 ветвления сделаны верно

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_1.py
> +    else:
💡 вот этот `else` можно не использовать - ведь из всех предыдущих веток цикла мы выйдем с помощью `return`

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +    #string1 = str(string1)
💡  закомментированные строчки удаляй

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +    if string1 != str(string1) or string2 != str(string2):
🔴 не самая лучшая проверка на типы - хоть и рабочая :)
для проверки можно использовать:

```python
type(string1) == str  # первый вариант
isinstance(string1, str)  # второй вариант - более интересный
```

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +    if str(string1) == str(string2):
💡 можно уже не приводить их к строке - это лишнее - до этого места в коде доберуться только строки

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +    if string1 != string2 and len(string1) > len(string2):
💡 уже не надо сравнивать строки на равенство - выше проверили ведь

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +    if string1 != string2 and len(string1) < len(string2):
🔴 тут нужно проверять на `вторая строка learn`

2022-09-16 18:20 UTC, vppuzakov commented on if_lesson_2.py
> +print(string_checking('temp_var', temp_var))
👍 молодец - тесты на разные кейсы (можно еще использовать assert)

```python
assert string_checking('test', 1) == 0
```

2022-09-16 18:20 UTC, vppuzakov commented on while_2.py
> +questions_and_answers = {"Как дела": "Хорошо!", "Что делаешь?": "Программирую", "На Python?": "Ага",
💡 попробуй переименовать, чтобы код стал попроще, например `answers = {...}`

2022-09-16 18:20 UTC, vppuzakov commented on while_2.py
> +        answers_dict = input('Задай вопрос кожаный! ')
👍 отличный вопрос

💡 переменную надо назвать соответствующе: `question`

2022-09-16 18:20 UTC, vppuzakov commented on while_2.py
> +        if answers_dict in questions_and_answers.keys():
🔴 крайне неэффективно проверять наличие переменной внутри `keys`

Гораздо лучше использовать сразу in и искать в словаре:

```python
if question in asnwers:
    ...
```

Еще вариант сразу попробовать достать значение словаря через get:

```python
answer = answers.get(question)
if answer:
    ...
```

2022-09-16 18:20 UTC, vppuzakov commented on while_2.py
>  def ask_user(answers_dict):
👍 В целом сделано верно, но есть ньюанс

2022-09-16 18:20 UTC, vppuzakov commented on while_1.py
> +    while True:
💡 старайся не использовать while True, когда есть условие выхода из цикла - пока не скажет хорошо в нашем случае. Лучше и использовать его:

```python
phrase = ''
while phrase != 'Хорошо':
    phrase = input('...')
```

Можно даже не использовать переменную:

```python
while input('') != 'Хорошо':
   pass
```

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +def total_number_of_sales(product):
👍 функция написано верно

💡 можно было вместо нее сразу использовать готовую `sum` - попробуй

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +def avg_number_of_sales(product):
👍 тоже верно работает - но лишняя - зачем нам дважды считать сумму по списку - тяжело. Лучше один раз где-то посчитать и уже ее использовать, поделив на длину списка

```python
total_sum = sum(sales)
avg_sum = total_sum / len(sales)
```

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +for one_product in phones:
💡 крайне важно соблюдать названия переменных - тебе же проще будет:

```python
for phone in phones:
    ...
    
# или

for product in products:
    ...
```

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +    print(f'Суммарное количество продаж для {one_product["product"]}: {product_sum}')
👍

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +    avg_phones += product_avg
🔴  верно только в нашем примере, но на самом деле математически не очень верно складывать средние значения чтобы потом посчитать общее среднее - лучше посчитать общую сумму и общее число элементов и уже в конце поделить

2022-09-16 18:20 UTC, vppuzakov commented on for_lesson.py
> +    sum_phones = 0
🔴  Так у нас явно задублировался код который выше и который в main - надо оставить только тот что в main

2022-10-02 14:00 UTC, opro12 commented
Провел работу над ошибками

2022-10-02 15:16 UTC, vppuzakov approved these changes

2022-10-02 15:16 UTC, vppuzakov commented on for_lesson.py
> +        count_phone = count_phone + len(phone['items_sold'])
+= предпочтительнее

2022-10-02 15:16 UTC, vppuzakov commented on if_lesson_2.py
> +    if type(string1) != str or type(string2) != str:
еще можно использовать isinstance(string1, str) - учитывает еще родителей

2022-10-02 15:16 UTC, vppuzakov commented on while_2.py
> +        if question in answers:
👍 
еще можно было бы использовать 

answer = answers.get(question)
if answer:
    ...

2022-10-02 15:23 UTC, merged